/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./frontend/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background":                 "#0d0d1a",
        "surface":                    "#16213e",
        "surface-dim":                "#10112a",
        "surface-bright":             "#363752",
        "surface-container-lowest":   "#0a0b25",
        "surface-container-low":      "#181933",
        "surface-container":          "#1c1d37",
        "surface-container-high":     "#272842",
        "surface-container-highest":  "#31324d",
        "surface-variant":            "#31324d",
        "primary":                    "#00d4ff",
        "primary-fixed":              "#b4ebff",
        "primary-fixed-dim":          "#3cd7ff",
        "primary-container":          "#00d4ff",
        "on-primary":                 "#003642",
        "on-primary-fixed":           "#001f27",
        "on-primary-fixed-variant":   "#004e5f",
        "on-primary-container":       "#00586b",
        "inverse-primary":            "#00677e",
        "secondary":                  "#bbc5eb",
        "secondary-fixed":            "#dae1ff",
        "secondary-fixed-dim":        "#bbc5eb",
        "secondary-container":        "#3b4665",
        "on-secondary":               "#252f4d",
        "on-secondary-fixed":         "#0f1a37",
        "on-secondary-fixed-variant": "#3b4665",
        "on-secondary-container":     "#aab4d9",
        "tertiary":                   "#ffd9a1",
        "tertiary-fixed":             "#ffdeae",
        "tertiary-fixed-dim":         "#ffba3d",
        "tertiary-container":         "#feb528",
        "on-tertiary":                "#432c00",
        "on-tertiary-fixed":          "#281900",
        "on-tertiary-fixed-variant":  "#604100",
        "on-tertiary-container":      "#6c4900",
        "error":                      "#ffb4ab",
        "error-container":            "#93000a",
        "on-error":                   "#690005",
        "on-error-container":         "#ffdad6",
        "on-surface":                 "#e1e0ff",
        "on-surface-variant":         "#bbc9cf",
        "on-background":              "#e1e0ff",
        "inverse-surface":            "#e1e0ff",
        "inverse-on-surface":         "#2d2e49",
        "outline":                    "#859398",
        "outline-variant":            "#3c494e",
        "surface-tint":               "#3cd7ff",
        /* ── v7 Ultra-Precision ── */
        "v7-cyan":                    "#00d4ff",
        "bg-overlay":                 "#0a0a12",
        "on-surface-alt":             "#dde3e7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "2xl":     "1rem",
        "card":    "12px",
        "full":    "9999px"
      },
      spacing: {
        "gutter":            "16px",
        "stack-sm":          "8px",
        "stack-md":          "16px",
        "stack-lg":          "24px",
        "stack-xl":          "32px",
        "poster-aspect":     "2/3",
        "container-margin":  "16px",
        "safe-bottom":       "env(safe-area-inset-bottom)",
        "control-height":    "44px",
        "list-row-height":   "56px",
        "nav-height":        "56px",
        "page-padding":      "16px",
        "section-gap":       "24px",
        /* ── v7 spacing ── */
        "margin-mobile":     "16px",
        "margin-desktop":    "20px",
        "nav-bottom-h":      "64px",
        "touch-target-min":  "44px",
        "nav-sidebar-w":     "240px"
      },
      fontFamily: {
        "sans":           ["system-ui", "sans-serif"],
        "display-lg":     ["system-ui", "sans-serif"],
        "headline-md":    ["system-ui", "sans-serif"],
        "headline-sm":    ["system-ui", "sans-serif"],
        "body-lg":        ["system-ui", "sans-serif"],
        "body-md":        ["system-ui", "sans-serif"],
        "label-caps":     ["ui-monospace", "monospace"],
        "score-label":    ["ui-monospace", "monospace"]
      },
      fontSize: {
        "display-lg":    ["32px", {"lineHeight":"1.2","letterSpacing":"-0.02em","fontWeight":"700"}],
        "headline-md":   ["24px", {"lineHeight":"1.3","letterSpacing":"-0.01em","fontWeight":"600"}],
        "headline-sm":   ["20px", {"lineHeight":"1.4","fontWeight":"600"}],
        "body-lg":       ["16px", {"lineHeight":"1.6","fontWeight":"400"}],
        "body-md":       ["14px", {"lineHeight":"1.5","fontWeight":"400"}],
        "label-caps":    ["12px", {"lineHeight":"1.2","letterSpacing":"0.05em","fontWeight":"600"}],
        "score-label":   ["18px", {"lineHeight":"1","fontWeight":"700"}],
        "page-title":    ["20px", {"lineHeight":"28px","fontWeight":"700"}],
        "card-title":    ["13px", {"lineHeight":"18px","fontWeight":"700"}],
        "secondary-info":["12px", {"lineHeight":"16px","fontWeight":"400"}],
        "section-header":["14px", {"lineHeight":"20px","letterSpacing":"0.05em","fontWeight":"600"}],
        "micro-label":   ["10px", {"lineHeight":"12px","fontWeight":"700"}]
      }
    }
  },
  plugins: []
}
